import { Platform, StyleSheet } from "react-native";
import { color, composer as composerMetrics, radius, space, type as typeTokens } from "@deep/design";

const androidText = Platform.OS === "android" ? { includeFontPadding: false as const } : {};

export function headerInitials(accountId: string | null, signedIn: boolean): string {
  if (!signedIn || !accountId) return "?";
  const compact = accountId.replace(/[^a-zA-Z0-9]/g, "");
  return (compact.slice(0, 2) || "DR").toUpperCase();
}

export function makeStyles(theme: (typeof color)["light"] | (typeof color)["dark"]) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.bg },
    header: { paddingHorizontal: space.sm, minHeight: 44, flexDirection: "row", alignItems: "center" },
    headerSide: { minWidth: 88, flexDirection: "row", alignItems: "center" },
    headerSideEnd: { justifyContent: "flex-end" },
    wordmark: { ...typeTokens.title, ...androidText, color: theme.ink, flex: 1, minWidth: 0, flexShrink: 1, textAlign: "center" },
    link: { color: theme.ink, fontSize: 16, lineHeight: 22, paddingVertical: 8, ...androidText },
    quietLink: { color: theme.muted, fontSize: 13, lineHeight: 18, paddingVertical: 6, ...androidText },
    error: { color: theme.danger, paddingHorizontal: space.lg, paddingVertical: space.sm, ...androidText },
    statusRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8, paddingVertical: space.sm, marginBottom: space.sm },
    statusText: { ...typeTokens.body, ...androidText, color: theme.muted, flexShrink: 1 },
    body: { flex: 1, paddingHorizontal: space.lg },
    libraryRow: { paddingVertical: 14, minHeight: 56, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line, flexDirection: "row", alignItems: "flex-start", gap: 12 },
    librarySearch: {
      ...typeTokens.body,
      ...androidText,
      color: theme.ink,
      backgroundColor: theme.composer.fill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.line,
      borderRadius: radius.md,
      paddingHorizontal: space.md,
      paddingVertical: 10,
      minHeight: 44,
      marginBottom: space.sm,
    },
    libraryPreview: { ...typeTokens.caption, ...androidText, color: theme.muted, marginTop: 4 },
    emptyHero: { paddingTop: 28, paddingBottom: space.sm },
    welcomeDisplay: { fontSize: 18, lineHeight: 24, fontWeight: "500" as const, letterSpacing: -0.2, ...androidText, color: theme.muted, marginBottom: space.md },
    exampleRow: { flexDirection: "column", alignItems: "flex-start", gap: 0 },
    exampleChip: { flexDirection: "row", alignItems: "center", paddingVertical: 6, minHeight: 44, justifyContent: "flex-start" },
    exampleChipText: { ...typeTokens.body, ...androidText, color: theme.muted },
    exampleTick: { width: 5, height: 5, borderRadius: 1, backgroundColor: theme.line, marginRight: 10 },
    card: { backgroundColor: "transparent", borderColor: "transparent", borderWidth: 0, borderRadius: 0, paddingVertical: space.sm, marginBottom: space.sm, overflow: "hidden" },
    clarifyCard: { backgroundColor: theme.surface, borderColor: theme.line, borderWidth: StyleSheet.hairlineWidth, borderRadius: radius.lg, paddingHorizontal: space.md, paddingVertical: space.sm, marginBottom: space.md, overflow: "hidden" },
    thinkingCard: { backgroundColor: "transparent", paddingVertical: space.sm, marginBottom: space.sm, overflow: "hidden" },
    thinkingStream: { paddingVertical: space.xs, marginBottom: space.md },
    sourceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: space.xs, paddingLeft: 20 },
    sourcePill: { backgroundColor: "transparent", paddingHorizontal: 0, paddingVertical: 0, borderRadius: 0 },
    sourcePillText: { ...typeTokens.caption, ...androidText, color: theme.muted },
    shimmer: { color: theme.thinking.ink },
    stopGlyph: { color: theme.stop.ink, fontSize: 12, fontWeight: "700" },
    attachHit: { width: composerMetrics.hit, height: composerMetrics.hit, alignItems: "center", justifyContent: "center" },
    sendHit: { width: composerMetrics.hit, height: composerMetrics.hit, alignItems: "center", justifyContent: "center" },
    userBubble: { alignSelf: "flex-end", maxWidth: "92%", backgroundColor: theme.userBubble.fill, borderRadius: radius.lg, paddingHorizontal: space.md, paddingVertical: space.sm, marginBottom: space.md },
    userBubbleText: { ...typeTokens.body, ...androidText, color: theme.userBubble.ink, flexShrink: 1 },
    reportBody: { marginBottom: space.md, paddingTop: space.xs },
    sheet: { flex: 1, backgroundColor: theme.surface, borderColor: theme.line, borderWidth: StyleSheet.hairlineWidth, borderRadius: radius.sheet, padding: space.md, marginHorizontal: space.sm, marginBottom: space.sm, maxWidth: "100%" },
    sheetHandle: { alignSelf: "center", width: 36, height: 4, borderRadius: 2, backgroundColor: theme.line, marginBottom: space.sm },
    sheetBody: { flex: 1, maxHeight: "100%" },
    sheetField: { marginBottom: space.sm },
    bounded: { width: "100%", maxWidth: "100%" },
    outline: { marginBottom: space.md, paddingBottom: space.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line, gap: 2 },
    outlineItem: { ...typeTokens.caption, ...androidText, color: theme.muted, paddingVertical: 8, minHeight: 36 },
    tableRow: { flexDirection: "row", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line },
    tableCell: { ...typeTokens.body, ...androidText, color: theme.ink, minWidth: 96, paddingVertical: 6, paddingRight: 12, flexShrink: 0 },
    tableHead: { ...typeTokens.caption, ...androidText, color: theme.muted, minWidth: 96, paddingVertical: 6, paddingRight: 12, textTransform: "uppercase", flexShrink: 0 },
    code: { fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace", fontSize: 13, lineHeight: 18, color: theme.ink, paddingVertical: 8 },
    quote: { ...typeTokens.body, ...androidText, color: theme.ink, fontStyle: "italic", paddingLeft: space.md, borderLeftWidth: 2, borderLeftColor: theme.accent },
    citeRow: { flexDirection: "row", flexWrap: "wrap", gap: 2, marginTop: 4 },
    citeLink: { paddingRight: 0 },
    citeChip: { color: theme.accent, overflow: "hidden", paddingHorizontal: 3, paddingVertical: 1, borderRadius: radius.sm, fontSize: 11, lineHeight: 14, fontWeight: "600", minHeight: 16, fontVariant: ["tabular-nums"] },
    answerText: { ...typeTokens.display, ...androidText, color: theme.ink, flexShrink: 1 },
    sampleMark: { ...typeTokens.meta, ...androidText, color: theme.muted, marginBottom: space.sm },
    kicker: { ...typeTokens.meta, ...androidText, color: theme.muted, marginBottom: 4, textTransform: "uppercase" },
    activityKicker: { ...typeTokens.caption, ...androidText, color: theme.thinking.ink, marginBottom: 8 },
    activityDetail: { ...typeTokens.caption, ...androidText, color: theme.thinking.ink, marginTop: 2 },
    activityLine: { ...typeTokens.body, ...androidText, color: theme.thinking.ink, flexShrink: 1 },
    title: { ...typeTokens.title, ...androidText, color: theme.ink, marginBottom: 6 },
    bodyText: { ...typeTokens.body, ...androidText, color: theme.ink, flexShrink: 1 },
    activityNow: { ...typeTokens.body, ...androidText, color: theme.thinking.inkActive, fontWeight: "600", flexShrink: 1 },
    jumpLatest: { ...typeTokens.caption, ...androidText, color: theme.accent, paddingVertical: 8, minHeight: 36 },
    activityItem: { flexDirection: "row", alignItems: "stretch", minHeight: 28 },
    activityRail: { width: 16, alignItems: "center" },
    activityTick: { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.thinking.ink, marginTop: 7 },
    activityTickNow: { width: 7, height: 7, borderRadius: 4, backgroundColor: theme.accent, marginTop: 6 },
    activityStem: { width: StyleSheet.hairlineWidth, flex: 1, backgroundColor: theme.thinking.rule, marginTop: 4 },
    activityCopy: { flex: 1, minWidth: 0, paddingBottom: 12, paddingLeft: 4 },
    caveat: { ...typeTokens.body, ...androidText, color: theme.caveat, marginTop: 8 },
    row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
    stopBtn: { alignSelf: "flex-start", marginTop: space.md, minWidth: 44, minHeight: 44, paddingHorizontal: 14, paddingVertical: 10, borderRadius: radius.md, backgroundColor: theme.stop.fill, justifyContent: "center" },
    stopLabel: { color: theme.stop.ink, fontWeight: "600", fontSize: 15 },
    avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: theme.accentMuted, alignItems: "center", justifyContent: "center" },
    avatarText: { ...typeTokens.caption, ...androidText, color: theme.ink, fontWeight: "600", fontSize: 13 },
    headerAvatar: { width: 28, height: 28, borderRadius: 14, backgroundColor: theme.accentMuted, alignItems: "center", justifyContent: "center" },
    headerAvatarText: { ...typeTokens.meta, ...androidText, color: theme.ink, fontWeight: "600" },
    section: { marginBottom: space.lg, paddingBottom: space.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line },
    switchRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: space.sm, minHeight: 56 },
    settingsRow: { minHeight: 56, justifyContent: "center", paddingVertical: 8 },
    segment: { flexDirection: "row", backgroundColor: "transparent", borderWidth: StyleSheet.hairlineWidth, borderColor: theme.line, borderRadius: radius.md, overflow: "hidden", marginBottom: space.sm },
    segmentOn: { color: theme.ink, fontWeight: "600", fontSize: 14, ...androidText },
    segmentOff: { color: theme.muted, fontSize: 14, ...androidText },
    composerDock: {
      paddingHorizontal: composerMetrics.gutter,
      paddingTop: space.sm,
      paddingBottom: space.xs,
      backgroundColor: theme.bg,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.line,
    },
    composerWrap: {
      flexDirection: "row",
      alignItems: "flex-end",
      minHeight: composerMetrics.visualHeight,
      paddingLeft: 4,
      paddingRight: 4,
      paddingVertical: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.composer.border,
      backgroundColor: theme.composer.fill,
      borderRadius: composerMetrics.radius,
      overflow: "visible",
    },
    composer: {
      flex: 1,
      minHeight: composerMetrics.visualHeight - 16,
      maxHeight: composerMetrics.inputLineHeight * composerMetrics.maxLines,
      fontSize: composerMetrics.inputSize,
      lineHeight: composerMetrics.inputLineHeight,
      fontWeight: "400" as const,
      ...androidText,
      color: theme.composer.ink,
      paddingHorizontal: space.sm,
      paddingVertical: 7,
      textAlignVertical: "center",
    },
    headerIconHit: { minWidth: 44, minHeight: 44, alignItems: "center", justifyContent: "center" },
    sendBtn: { backgroundColor: theme.composer.sendFill, paddingHorizontal: 12, paddingVertical: 6, borderRadius: radius.md, justifyContent: "center" },
    sendBtnOff: { backgroundColor: theme.composer.sendFillDisabled, paddingHorizontal: 12, paddingVertical: 6, borderRadius: radius.md, justifyContent: "center" },
    sendBtnIcon: { backgroundColor: theme.composer.sendFill, width: composerMetrics.sendVisible, height: composerMetrics.sendVisible, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    sendBtnIconOff: { backgroundColor: theme.composer.sendFillDisabled, width: composerMetrics.sendVisible, height: composerMetrics.sendVisible, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    sendBtnQuiet: { backgroundColor: "transparent", width: composerMetrics.sendVisible, height: composerMetrics.sendVisible, borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.composer.border, alignItems: "center", justifyContent: "center" },
    stopBtnIcon: { backgroundColor: theme.stop.fill, width: composerMetrics.sendVisible, height: composerMetrics.sendVisible, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    send: { color: theme.composer.sendInk, fontWeight: "600", fontSize: 15, ...androidText },
    sendOff: { color: theme.composer.sendInkDisabled, fontWeight: "600", fontSize: 15, ...androidText },
    attachMark: { color: theme.composer.ink, fontSize: 22, lineHeight: 26, width: 44, textAlign: "center" },
    followRow: { flexDirection: "column", gap: 0, paddingHorizontal: space.md, paddingBottom: 2 },
    followChipHit: { minHeight: 28, justifyContent: "center", maxWidth: "100%" },
    followChip: { color: theme.muted, overflow: "hidden", paddingVertical: 2, fontSize: 14, lineHeight: 18, ...androidText },
    input: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.composer.border,
      borderRadius: radius.md,
      paddingHorizontal: space.md,
      paddingVertical: 6,
      color: theme.composer.ink,
      marginBottom: 8,
      backgroundColor: theme.composer.fill,
      minHeight: 36,
      ...typeTokens.body,
      ...androidText,
    },
    attachSheet: { marginHorizontal: space.md, marginBottom: space.sm, padding: space.md, backgroundColor: theme.surface, borderColor: theme.line, borderWidth: StyleSheet.hairlineWidth, borderRadius: radius.md },
    attachAction: { minHeight: 44, justifyContent: "center", paddingVertical: 4 },
  });
}
