import { Platform, StyleSheet } from "react-native";
import { color, radius, space, type as typeTokens } from "@deep/design";

export function headerInitials(accountId: string | null, signedIn: boolean): string {
  if (!signedIn || !accountId) return "?";
  const compact = accountId.replace(/[^a-zA-Z0-9]/g, "");
  return (compact.slice(0, 2) || "DR").toUpperCase();
}

export function makeStyles(theme: (typeof color)["light"] | (typeof color)["dark"]) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.bg },
    header: { paddingHorizontal: space.sm, minHeight: 44, flexDirection: "row", alignItems: "center" },
    headerSide: { minWidth: 88, flexDirection: "row", alignItems: "center" },
    headerSideEnd: { justifyContent: "flex-end" },
    wordmark: { ...typeTokens.title, color: theme.ink, flex: 1, minWidth: 0, flexShrink: 1, fontSize: 17, lineHeight: 22, textAlign: "center" },
    link: { color: theme.ink, fontSize: 16, paddingVertical: 8 },
    quietLink: { color: theme.muted, fontSize: 15, paddingVertical: 8 },
    error: { color: theme.danger, paddingHorizontal: space.lg, paddingVertical: space.sm },
    statusRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 12, paddingVertical: space.sm, marginBottom: space.sm },
    statusText: { ...typeTokens.body, color: theme.muted, flexShrink: 1 },
    body: { flex: 1, paddingHorizontal: space.lg },
    emptyHero: { paddingTop: 28, paddingBottom: space.md },
    welcomeDisplay: { ...typeTokens.title, color: theme.ink, marginBottom: space.sm },
    exampleRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    exampleChip: { backgroundColor: "transparent", paddingHorizontal: 2, paddingVertical: 8, minHeight: 44, justifyContent: "center" },
    exampleChipText: { ...typeTokens.caption, color: theme.muted },
    card: { backgroundColor: theme.surface, borderColor: theme.line, borderWidth: 1, borderRadius: 20, padding: space.lg, marginBottom: space.md, overflow: "hidden" },
    clarifyCard: { backgroundColor: theme.surface, borderColor: theme.line, borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, paddingHorizontal: space.md, paddingVertical: space.sm, marginBottom: space.md, overflow: "hidden" },
    thinkingCard: { backgroundColor: "transparent", paddingVertical: space.sm, marginBottom: space.sm, overflow: "hidden" },
    thinkingStream: { paddingVertical: space.xs, marginBottom: space.sm },
    sourceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: space.sm },
    sourcePill: { backgroundColor: theme.accentMuted, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
    sourcePillText: { ...typeTokens.caption, color: theme.ink },
    shimmer: { color: theme.thinking.ink },
    stopGlyph: { color: theme.stop.ink, fontSize: 12, fontWeight: "700" },
    attachHit: { minWidth: 44, minHeight: 44, alignItems: "center", justifyContent: "center" },
    userBubble: { alignSelf: "flex-end", maxWidth: "92%", backgroundColor: theme.userBubble.fill, borderRadius: 18, paddingHorizontal: space.md, paddingVertical: space.sm, marginBottom: space.md },
    userBubbleText: { ...typeTokens.body, color: theme.userBubble.ink, flexShrink: 1 },
    reportBody: { marginBottom: space.md, paddingTop: space.sm },
    sheet: { flex: 1, backgroundColor: theme.surface, borderColor: theme.line, borderWidth: 1, borderRadius: 24, padding: space.lg, marginHorizontal: space.md, marginBottom: space.md, maxWidth: "100%" },
    sheetBody: { flex: 1, maxHeight: "100%" },
    bounded: { width: "100%", maxWidth: "100%" },
    outline: { marginBottom: space.sm, paddingBottom: space.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line },
    outlineItem: { ...typeTokens.caption, color: theme.muted, marginBottom: 0 },
    tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: theme.line },
    tableCell: { ...typeTokens.body, color: theme.ink, minWidth: 96, paddingVertical: 8, paddingRight: 12, flexShrink: 0 },
    tableHead: { ...typeTokens.caption, color: theme.muted, minWidth: 96, paddingVertical: 8, paddingRight: 12, textTransform: "uppercase", flexShrink: 0 },
    code: { fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace", fontSize: 13, color: theme.ink, paddingVertical: 8 },
    quote: { ...typeTokens.body, color: theme.ink, fontStyle: "italic", paddingLeft: space.md, borderLeftWidth: 2, borderLeftColor: theme.accent },
    citeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
    citeLink: { paddingRight: 0 },
    citeChip: { backgroundColor: theme.accentMuted, color: theme.ink, overflow: "hidden", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, fontSize: 13, minHeight: 32 },
    answerText: { ...typeTokens.body, color: theme.ink, flexShrink: 1, fontWeight: "600" },
    sampleMark: { ...typeTokens.caption, color: theme.muted, marginBottom: space.sm },
    kicker: { ...typeTokens.caption, color: theme.muted, marginBottom: 8 },
    activityKicker: { ...typeTokens.caption, color: theme.thinking.ink, marginBottom: 8 },
    activityDetail: { ...typeTokens.caption, color: theme.thinking.ink, marginTop: 4 },
    activityLine: { ...typeTokens.body, color: theme.thinking.ink, flexShrink: 1 },
    title: { ...typeTokens.title, color: theme.ink, marginBottom: 8 },
    bodyText: { ...typeTokens.body, color: theme.ink, flexShrink: 1 },
    activityNow: { ...typeTokens.body, color: theme.thinking.inkActive, fontWeight: "600", flexShrink: 1 },
    activityItem: { marginTop: space.sm, paddingTop: space.sm, borderTopWidth: 1, borderTopColor: theme.thinking.rule },
    caveat: { ...typeTokens.body, color: theme.caveat, marginTop: 8 },
    row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
    stopBtn: { alignSelf: "flex-start", marginTop: space.md, minWidth: 44, minHeight: 44, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, backgroundColor: theme.stop.fill, justifyContent: "center" },
    stopLabel: { color: theme.stop.ink, fontWeight: "600", fontSize: 15 },
    avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: theme.accentMuted, alignItems: "center", justifyContent: "center" },
    avatarText: { ...typeTokens.caption, color: theme.ink, fontWeight: "600", fontSize: 16 },
    headerAvatar: { width: 32, height: 32, borderRadius: 16, backgroundColor: theme.accentMuted, alignItems: "center", justifyContent: "center" },
    headerAvatarText: { ...typeTokens.caption, color: theme.ink, fontWeight: "600", fontSize: 12 },
    section: { marginBottom: space.lg, paddingBottom: space.md, borderBottomWidth: 1, borderBottomColor: theme.line },
    switchRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: space.sm, minHeight: 44 },
    segment: { flexDirection: "row", backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.line, borderRadius: radius.md, overflow: "hidden", marginBottom: space.sm },
    segmentOn: { color: theme.ink, fontWeight: "600", fontSize: 15 },
    segmentOff: { color: theme.muted, fontSize: 15 },
    composerDock: { paddingHorizontal: space.md, paddingTop: space.xs, paddingBottom: space.xs, backgroundColor: theme.bg },
    composerWrap: { flexDirection: "row", alignItems: "flex-end", paddingLeft: 4, paddingRight: 4, paddingVertical: 4, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.composer.border, backgroundColor: theme.composer.fill, borderRadius: radius.pill, shadowColor: theme.ink, shadowOpacity: 0.04, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
    composer: { flex: 1, minHeight: 36, maxHeight: 180, ...typeTokens.body, color: theme.composer.ink, paddingHorizontal: space.sm, paddingVertical: 8 },
    headerIconHit: { minWidth: 48, minHeight: 48, alignItems: "center", justifyContent: "center" },
    sendBtn: { backgroundColor: theme.composer.sendFill, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, justifyContent: "center" },
    sendBtnOff: { backgroundColor: theme.composer.sendFillDisabled, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, justifyContent: "center" },
    sendBtnIcon: { backgroundColor: theme.composer.sendFill, width: 28, height: 28, borderRadius: 14, alignItems: "center", justifyContent: "center" },
    sendBtnIconOff: { backgroundColor: theme.composer.sendFillDisabled, width: 28, height: 28, borderRadius: 14, alignItems: "center", justifyContent: "center" },
    sendBtnQuiet: { backgroundColor: "transparent", width: 28, height: 28, borderRadius: 14, alignItems: "center", justifyContent: "center" },
    stopBtnIcon: { backgroundColor: theme.stop.fill, width: 28, height: 28, borderRadius: 6, alignItems: "center", justifyContent: "center" },
    send: { color: theme.composer.sendInk, fontWeight: "600", fontSize: 15 },
    sendOff: { color: theme.composer.sendInkDisabled, fontWeight: "600", fontSize: 15 },
    attachMark: { color: theme.composer.ink, fontSize: 22, lineHeight: 26, width: 44, textAlign: "center" },
    followRow: { flexDirection: "column", gap: 0, paddingHorizontal: space.md, paddingBottom: 2 },
    followChipHit: { minHeight: 28, justifyContent: "center", maxWidth: "100%" },
    followChip: { color: theme.muted, overflow: "hidden", paddingVertical: 2, fontSize: 14, lineHeight: 18 },
    input: { borderWidth: StyleSheet.hairlineWidth, borderColor: theme.composer.border, borderRadius: radius.pill, paddingHorizontal: space.md, paddingVertical: 8, color: theme.composer.ink, marginBottom: 8, backgroundColor: theme.composer.fill, minHeight: 36 },
    attachSheet: { marginHorizontal: space.md, marginBottom: space.sm, padding: space.md, backgroundColor: theme.surface, borderColor: theme.line, borderWidth: 1, borderRadius: radius.md },
    attachAction: { minHeight: 44, justifyContent: "center", paddingVertical: 4 },
  });
}

