const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { createRequire } = require('node:module');
const cwd = '/tmp/deep-v6-uuid-root-5fbec3a';
const req = createRequire(path.join(cwd, 'package.json'));
const xcode = req('xcode');
const xreq = createRequire(req.resolve('xcode'));
const uuid = xreq('uuid');
const uuidPackage = JSON.parse(fs.readFileSync(path.join(path.dirname(xreq.resolve('uuid')), '../../package.json'), 'utf8'));
assert.equal(uuidPackage.version, '11.1.1');
const file = '/tmp/deep-v6-uuid-root-synthetic.pbxproj';
fs.writeFileSync(file, `// !$*UTF8*$!\n{ archiveVersion = 1; classes = {}; objectVersion = 56; objects = {\n/* Begin PBXBuildFile section */\n/* End PBXBuildFile section */\n/* Begin PBXFileReference section */\n/* End PBXFileReference section */\n/* Begin PBXGroup section */\nAAAAAAAAAAAAAAAAAAAAAAAA = { isa = PBXGroup; children = (); sourceTree = "<group>"; };\n/* End PBXGroup section */\n/* Begin PBXProject section */\nBBBBBBBBBBBBBBBBBBBBBBBB = { isa = PBXProject; mainGroup = AAAAAAAAAAAAAAAAAAAAAAAA; targets = (); };\n/* End PBXProject section */\n}; rootObject = BBBBBBBBBBBBBBBBBBBBBBBB; }\n`);
const project = xcode.project(file).parseSync();
const group = project.addPbxGroup(['Synthetic.swift'], 'Synthetic', 'Synthetic');
project.hash.project.objects.PBXGroup.AAAAAAAAAAAAAAAAAAAAAAAA.children.push({ value: group.uuid, comment: 'Synthetic' });
const ids = Array.from({length:1000}, () => project.generateUuid());
assert(ids.every(id => /^[A-F0-9]{24}$/.test(id)));
assert.equal(new Set(ids).size, 1000);
assert.match(uuid.v4(), /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
for (const algorithm of ['v3', 'v5']) assert.throws(() => uuid[algorithm]('test', uuid[algorithm].DNS, new Uint8Array(1), 0), RangeError);
fs.writeFileSync(file, project.writeSync());
const restored = xcode.project(file).parseSync();
assert.equal(restored.hash.project.rootObject, 'BBBBBBBBBBBBBBBBBBBBBBBB');
assert.equal(restored.hash.project.objects.PBXGroup[group.uuid].name, 'Synthetic');
assert.equal(restored.hash.project.objects.PBXGroup[group.uuid].children.length, 1);
assert(Object.values(restored.hash.project.objects.PBXFileReference).some(v => v && typeof v === 'object' && String(v.path).includes('Synthetic.swift')));
console.log(JSON.stringify({xcode: req('xcode/package.json').version, uuid: uuidPackage.version, resolvedUuid: xreq.resolve('uuid'), roundtrip: 'pass', generatedIds: ids.length, sampledUnique: new Set(ids).size, invalidBufferV3V5: 'RangeError', nativeBuild: false}, null, 2));
