// Own-project metadata only. No credentials, questions, raw OS/UI data, or global Expo cleanup.
const {createRequire}=require('node:module');
const req=createRequire('/tmp/deep-v6-metro-6490546/package.json');
const WebSocket=req('ws');
(async()=>{
 const targets=await(await fetch('http://127.0.0.1:8081/json/list')).json();
 if(targets.length!==1||!targets[0].title.startsWith('host.exp.exponent'))throw Error('Own Expo runtime inaccessible or ambiguous');
 const ws=new WebSocket(targets[0].webSocketDebuggerUrl);await new Promise((ok,no)=>{ws.once('open',ok);ws.once('error',no)});let id=0;
 function evaluate(expression){return new Promise((ok,no)=>{const n=++id,t=setTimeout(()=>{ws.off('message',read);no(Error('Native deadline'))},10000);function read(b){const r=JSON.parse(b);if(r.id!==n)return;clearTimeout(t);ws.off('message',read);if(r.result?.exceptionDetails)no(Error('Own project expression failed'));else ok(r.result?.result?.value)}ws.on('message',read);ws.send(JSON.stringify({id:n,method:'Runtime.evaluate',params:{expression,returnByValue:true}}))})}
 try {
 await evaluate(`(()=>{globalThis.__deepCompatResult=null;(async()=>{const entries=Array.from(__r.getModules().entries());const find=n=>{const m=entries.find(x=>x[1].verboseName===n);if(!m)throw Error('Project module unavailable');return __r(m[0]);};if(find('src/api.ts').backendUrl!=='http://127.0.0.1:8787')throw Error('Wrong backend');const sm=entries.find(x=>/expo-secure-store.*[\\/]build[\\/]SecureStore.js$/.test(x[1].verboseName||''));if(!sm)throw Error('Native storage unavailable');const secure=__r(sm[0]);const raw=await secure.getItemAsync('deep.session.v2',{keychainService:'deep.research.session.v2',keychainAccessible:secure.WHEN_UNLOCKED_THIS_DEVICE_ONLY});if(!raw)return {runtimeLoaded:true,accountMatched:false,cleanupAttempted:false};const session=JSON.parse(raw);if(session.accountId!=='1617411b-d6bd-4aeb-98b4-9f0ebb5197e3')return {runtimeLoaded:true,accountMatched:false,cleanupAttempted:false};const storage=find('src/native-session.ts').sessionStorage;await storage.clear();const after=await storage.hydrate();return {runtimeLoaded:true,accountMatched:true,cleanupAttempted:true,sessionCleared:!after.token&&!after.accountId,reportCleared:!after.state.report&&!after.state.previousReport,requestsCleared:!after.state.pendingAdmission&&!after.state.pendingVerification&&!after.state.pendingSourceDeletion,draftsCleared:after.state.draft.length===0&&!after.state.correctionDraft};})().then(value=>globalThis.__deepCompatResult={ok:true,value},()=>globalThis.__deepCompatResult={ok:false,cleanupConfirmed:false});return 'started';})()`);
 let r;for(let n=0;n<100;n++){r=await evaluate('globalThis.__deepCompatResult');if(r)break;await new Promise(ok=>setTimeout(ok,100))}if(!r)throw Error('Native async deadline');console.log(JSON.stringify(r,null,2));await evaluate('delete globalThis.__deepCompatResult');if(!r.ok)process.exitCode=1;
 }finally{ws.close()}
})().catch(e=>{console.error(e.message);process.exitCode=1});
