import {beforeAll,afterAll,afterEach,it,expect,vi} from "vitest";
import type pg from "pg";
import {CreateRunRequestSchema} from "@deep/contracts";
import {createPool,migrate,withTx} from "../src/platform/db.js";
import {createDevSession,grantConsent} from "../src/modules/access.js";
import {admitRun} from "../src/modules/run-admission.js";
import {claimLease,cancelRun} from "../src/modules/runs.js";
import {adoptSearchSources} from "../src/modules/search-sources.js";
import {reconcileProviderIntent} from "../src/modules/provider-reconciliation.js";
import {ensureResearchTask} from "../src/worker/research-task.js";
import {performPublicSearch} from "../src/worker/public-search.js";
import {fencedSession} from "../src/worker/fenced-session.js";
import {loadConfig} from "../src/platform/config.js";
import {AZURE_ZDR_EXACT_QUOTE_POLICY,AZURE_ZDR_DISCOVERY_POLICY,STRUCTURED_MODEL_POLICY} from "../src/ports/model-policy.js";
import {discoveryPolicyForNewSearch,discoveryModelPolicy,AZURE_DISCOVERY_POLICY,DEEP_DISCOVERY_POLICY} from "../src/ports/search.js";
let pool:pg.Pool;const originalFetch=globalThis.fetch;
beforeAll(async()=>{if(!process.env.TEST_DATABASE_URL)throw Error("Explicit isolated test database required");pool=createPool(process.env.TEST_DATABASE_URL);await migrate(pool);});
afterEach(()=>{globalThis.fetch=originalFetch;});afterAll(async()=>{await pool.end();});
const question="Compare coral and kelp restoration.",span={start:0,end:question.length,quote:question};
const scope={entity:null,plan:null,version:null,geography:null,time:null,population:null};
const brief={objective:question,objectiveProvenance:span,intendedOutput:"comparison",criteria:[{key:"c1",description:question,field:"restoration",operator:"compare",value:null,unit:null,importance:"hard",scope,provenance:span,group:"all",groupOperator:"all",unresolvedAlternatives:[]}],questions:[{key:"q1",text:question,criterionKeys:["c1"],importance:"critical",evidenceStandard:"documented outcomes"}],assumptions:[],openAmbiguities:[],explicitExclusions:[]};
const envelope=(provider:string,content:unknown)=>new Response(JSON.stringify({id:crypto.randomUUID(),model:"openai/gpt-4o-mini",provider,usage:{cost:"0.000001"},choices:[{finish_reason:"stop",message:{content:JSON.stringify(content)}}]}));
it.each([AZURE_ZDR_EXACT_QUOTE_POLICY,AZURE_ZDR_DISCOVERY_POLICY])("pins and replays discovery under $id despite current config, and binds adoption",async policy=>{
 const account=await withTx(pool,async db=>{const a=await createDevSession(db);await grantConsent(db,a.accountId);return a;});
 const {runId}=await admitRun(pool,account.accountId,crypto.randomUUID(),CreateRunRequestSchema.parse({question,routeMode:"controlled-research"}),{modelPolicyId:policy.id});
 const owner=crypto.randomUUID(),fence=(await claimLease(pool,runId,owner,30000))!;
 const session=fencedSession(pool,{runId,accountId:account.accountId,owner,fence,briefRevision:1,leaseMs:30000});
 const config=loadConfig({DATABASE_URL:process.env.TEST_DATABASE_URL!,LIVE_ROUTE_ENABLED:"true",STRUCTURED_MODEL_ENABLED:"true",STRUCTURED_DISCOVERY_ENABLED:"true",STRUCTURED_MODEL_POLICY_ID:STRUCTURED_MODEL_POLICY.id,OPENROUTER_API_KEY:`nonbillable-${crypto.randomUUID()}`,LIVE_SPEND_CAP_MICRO:"1000000",LIVE_KEY_SPEND_CAP_MICRO:"1000000000",LIVE_BUDGET_SCOPE:crypto.randomUUID()});
 try{
  globalThis.fetch=vi.fn(async()=>envelope("Azure",brief));
  const task=await ensureResearchTask(pool,config,session,{runId,accountId:account.accountId,fence,briefRevision:1});if(task.kind!=="task")throw Error("test_task_unavailable");
  const searchPolicy=discoveryPolicyForNewSearch(policy.id),provider=discoveryModelPolicy(searchPolicy.id);
  const send=vi.fn(async(_url:Parameters<typeof fetch>[0],init?:RequestInit)=>{
   const body=JSON.parse(String(init?.body));expect(body.provider.only).toEqual([provider.provider]);
   expect(body.provider.zdr).toBe(provider.provider==="azure"?true:undefined);
   return new Response(JSON.stringify({id:crypto.randomUUID(),model:provider.model,provider:provider.providerName,usage:{cost:"0.000003"},choices:[{finish_reason:"stop",message:{annotations:[{type:"url_citation",url_citation:{url:"https://example.org/study",title:"Study",content:"Restoration findings"}}]}}]}));
  });globalThis.fetch=send;
  const args={runId,accountId:account.accountId,fence,briefRevision:1,taskId:task.task.id,proposal:{rationale:"Public evidence",action:{type:"search",query:"coral kelp restoration",questionKeys:["q1"],publicQueryBasis:span}}};
  const first=await performPublicSearch(pool,config,session,args);expect(first).toMatchObject({kind:"search",reused:false});
  expect(await performPublicSearch(pool,config,session,args)).toMatchObject({kind:"search",reused:true});expect(send).toHaveBeenCalledTimes(1);
  if(first.kind!=="search")throw Error("test_search_unavailable");
  const originalReceipt=(await pool.query("SELECT receipt FROM provider_intents WHERE id=$1",[first.intentId])).rows[0].receipt;
  const generation={version:"openrouter-generation-cost.v1" as const,providerId:originalReceipt.providerId,model:provider.model,provider:provider.providerName,actualMicro:3,rawCost:"0.000003",retrievedAt:new Date().toISOString(),responseDigest:"a".repeat(64)};
  await expect(reconcileProviderIntent(pool,config,first.intentId,async()=>({kind:"receipt",receipt:{...generation,provider:provider.providerName==="Azure"?"OpenAI":"Azure"}}),new AbortController().signal)).rejects.toThrow("receipt_route_or_cost_mismatch");
  expect(await reconcileProviderIntent(pool,config,first.intentId,async()=>({kind:"receipt",receipt:generation}),new AbortController().signal)).toMatchObject({kind:"reconciled",actualMicro:3});
  expect((await pool.query("SELECT receipt FROM provider_intents WHERE id=$1",[first.intentId])).rows[0].receipt).toEqual(originalReceipt);
  expect((await pool.query("SELECT policy_id FROM search_operations WHERE intent_id=$1",[first.intentId])).rows).toEqual([{policy_id:searchPolicy.id}]);
  const adopted=await session.write(db=>adoptSearchSources(db,{...args,intentId:first.intentId}));expect(adopted).toHaveLength(1);
  const otherPolicy=searchPolicy.id===AZURE_DISCOVERY_POLICY.id?DEEP_DISCOVERY_POLICY:AZURE_DISCOVERY_POLICY;
  await pool.query("UPDATE search_operations SET policy_id=$2 WHERE intent_id=$1",[first.intentId,otherPolicy.id]);
  await expect(session.write(db=>adoptSearchSources(db,{...args,intentId:first.intentId}))).rejects.toThrow("search_result_not_adoptable");
  await pool.query("UPDATE search_operations SET policy_id=$2 WHERE intent_id=$1",[first.intentId,searchPolicy.id]);
  globalThis.fetch=vi.fn(async()=>{throw Error("Synthetic lost acknowledgement");});
  const changed={...args,proposal:{...args.proposal,action:{...args.proposal.action,query:"kelp restoration"}}};
  expect(await performPublicSearch(pool,config,session,changed)).toMatchObject({kind:"pending"});
  expect(await performPublicSearch(pool,config,session,changed)).toMatchObject({kind:"pending"});expect(fetch).toHaveBeenCalledTimes(1);
  expect((await pool.query("SELECT reserved_max_micro::text,state FROM provider_intents WHERE run_id=$1 AND confirmed_micro IS NULL",[runId])).rows).toEqual([{reserved_max_micro:"9000",state:"outcome-unknown"}]);
 }finally{session.stop();await cancelRun(pool,runId);}
});
