import { createHash } from "node:crypto";
import { mkdir,writeFile,readFile,rm } from "node:fs/promises";
import { join } from "node:path";
import { afterAll,afterEach,beforeAll,expect,it,vi } from "vitest";
import type pg from "pg";
import type PgBoss from "pg-boss";
import type { FastifyInstance } from "fastify";
import { CorrectionRequestSchema,CreateRunRequestSchema } from "@deep/contracts";
import { createPool,migrate,withTx } from "../src/platform/db.js";
import { loadConfig } from "../src/platform/config.js";
import { buildApp } from "../src/api/app.js";
import { createQueue } from "../src/adapters/queue.js";
import * as extraction from "../src/adapters/extraction/offline.js";
import { createDevSession,deleteAccount,grantConsent,revokeConsent } from "../src/modules/access.js";
import { admitRun } from "../src/modules/run-admission.js";
import { admitResearchCorrection } from "../src/modules/research-corrections.js";
import { storeAttachment } from "../src/modules/attachments.js";
import { deleteSourceForAccount } from "../src/modules/source-deletion.js";
import { getPassageForAccount,insertExtractedVersion,insertSource,insertVersionAndPassage } from "../src/modules/evidence.js";
import { exportReportForAccount } from "../src/modules/report-export.js";
import { claimLease,getRun } from "../src/modules/runs.js";
import { reserveLiveAttempt,liveSpendUsedMicro } from "../src/modules/live-spend.js";
import { updateIntentState } from "../src/modules/billing.js";
import { fencedSession,LostWorkerLease } from "../src/worker/fenced-session.js";
import { ingestAttachments } from "../src/worker/attachment-ingestion.js";
import { performModelOperation } from "../src/worker/model-gateway.js";

let pool:pg.Pool,boss:PgBoss,app:FastifyInstance;
const accounts:string[]=[],sessions:ReturnType<typeof fencedSession>[]=[];
const originalFetch=globalThis.fetch;
const question="Compare synthetic wetland restoration evidence.";
const canary="SYNTHETIC_SOURCE_DELETE_CANARY";
const testUrl=process.env.TEST_DATABASE_URL??"postgres://deep:deep_local_dev_only@127.0.0.1:55432/deep_research_test";
const storageDir=`/tmp/deep-v6-source-deletion-${crypto.randomUUID()}`;
const config=loadConfig({DATABASE_URL:testUrl,NODE_ENV:"test",APP_AUTH_MODE:"development",LIVE_ROUTE_ENABLED:"true",STRUCTURED_MODEL_ENABLED:"true",
 STORAGE_DIR:storageDir,OPENROUTER_API_KEY:"nonbillable-test-key",LIVE_KEY_SPEND_CAP_MICRO:"1000000000",LIVE_SPEND_CAP_MICRO:"1000000",LIVE_BUDGET_SCOPE:crypto.randomUUID()});
beforeAll(async()=>{await mkdir(storageDir);pool=createPool(testUrl);await migrate(pool);boss=await createQueue(testUrl);app=await buildApp({pool,boss,config});});
afterEach(async()=>{
 globalThis.fetch=originalFetch;vi.restoreAllMocks();for(const session of sessions.splice(0))session.stop();
 for(const accountId of accounts.splice(0).reverse())await withTx(pool,async db=>{
  await deleteAccount(db,accountId);
  // Only accounts generated by this suite are removed; no shared-database truncation.
  for(const {id} of (await db.query("SELECT id FROM runs WHERE account_id=$1 ORDER BY created_at DESC",[accountId])).rows){
   for(const table of ["publication_attempts","reports","provider_intents","run_actions","run_leases","reservations","claims","passages"])
    await db.query(`DELETE FROM ${table} WHERE run_id=$1`,[id]);
   await db.query("DELETE FROM source_versions WHERE source_id IN(SELECT id FROM sources WHERE run_id=$1)",[id]);
   await db.query("DELETE FROM sources WHERE run_id=$1",[id]);
   await db.query("DELETE FROM runs WHERE id=$1",[id]);
  }
  for(const table of ["file_deletion_outbox","attachments","research_briefs","conversations","allowance_accounts","sessions","consent_records","tombstones"])
   await db.query(`DELETE FROM ${table} WHERE account_id=$1`,[accountId]);
  await db.query("DELETE FROM accounts WHERE id=$1",[accountId]);
 });
});
afterAll(async()=>{await app.close();await boss.stop({graceful:false,timeout:2000});await pool.end();await rm(storageDir,{recursive:true,force:true});});
async function account(){const result=await withTx(pool,async db=>{const s=await createDevSession(db);await grantConsent(db,s.accountId);return s;});accounts.push(result.accountId);return result;}
async function run(accountId:string,attachmentIds:string[]=[]){return admitRun(pool,accountId,crypto.randomUUID(),CreateRunRequestSchema.parse({question,routeMode:"controlled-research",attachmentIds}));}
async function lease(accountId:string,runId:string){const owner=crypto.randomUUID(),run=(await getRun(pool,runId))!,fence=(await claimLease(pool,runId,owner,30000))!;
 const session=fencedSession(pool,{accountId,runId,owner,fence,briefRevision:run.brief_revision,leaseMs:30000});sessions.push(session);return {session,fence};}
async function source(accountId:string,runId:string,locator="https://example.org/private-synthetic",text=canary){
 const sourceId=await insertSource(pool,{accountId,runId,locator,title:text,publisher:"Synthetic",originCluster:locator});
 const bytes=Buffer.from(text),digest=createHash("sha256").update(bytes).digest("hex");
 const document={version:"utf8-notes-v1" as const,digest,status:"extracted" as const,warnings:[],blocks:[{kind:"text" as const,locator:"paragraph:0",text,rows:[]}]};
 const versionId=await insertExtractedVersion(pool,{accountId,runId,sourceId,bytes,extraction:document,
  receipt:{requestedUrl:locator,finalUrl:locator,redirectChain:[],status:200,mime:"text/plain",retrievedAt:new Date().toISOString(),outcome:"successful_body"}});
 const passageId=(await pool.query("SELECT id FROM passages WHERE source_version_id=$1",[versionId])).rows[0].id as string;
 return {sourceId,versionId,passageId,document,bytes};
}
async function derived(accountId:string,runId:string,text=canary){
 const reportId=crypto.randomUUID();
 await pool.query(`INSERT INTO reports(id,run_id,account_id,version,outcome,basis,blocks,claim_ids,limitations,source_access_summary,change_summary,route_mode)
  VALUES($1,$2,$3,1,'completed_with_limitations','{}',$4,'{}',$5,$5,$6,'controlled-research')`,[reportId,runId,accountId,JSON.stringify([{text}]),JSON.stringify([text]),JSON.stringify({notes:text})]);
 const intentId=crypto.randomUUID();
 await pool.query("INSERT INTO provider_intents(id,run_id,correlation_id,route,request_digest,reserved_max_micro,state,confirmed_micro) VALUES($1::uuid,$2,$1::text,'openrouter:test',$3,1,'confirmed',1)",[intentId,runId,text]);
 await pool.query(`INSERT INTO model_operation_results(intent_id,run_id,account_id,operation,brief_revision,evidence_revision,request_digest,schema_version,prompt_version,policy_id,result,input_manifest)
  VALUES($1,$2,$3,'brief',1,0,$4,'test','test','test',$5,$5)`,[intentId,runId,accountId,text,JSON.stringify({privateCopiedText:text})]);
 return reportId;
}
const correction=(revision:number)=>CorrectionRequestSchema.parse({expectedBriefRevision:revision,correctionText:"Change the question",patch:{kind:"replace_question",question:"Compare corrected wetland evidence.",evidencePolicy:"reuse_snapshot"}});

it("W03/W06 deletes owned source and reused descendants, preserving unrelated raw evidence and accounts",async()=>{
 const owner=await account(),foreign=await account(),parent=await run(owner.accountId),unrelated=await run(owner.accountId),other=await run(foreign.accountId);
 const target=await source(owner.accountId,parent.runId),kept=await source(owner.accountId,parent.runId,"https://example.org/unrelated","KEEP_RAW_SAME_RUN");
 const child=await admitResearchCorrection(pool,owner.accountId,parent.runId,correction(1));
 const grandchild=await admitResearchCorrection(pool,owner.accountId,child.runId,correction(child.briefRevision));
 const independent=await source(owner.accountId,unrelated.runId,"https://example.org/independent","KEEP_INDEPENDENT");
 const foreignSource=await source(foreign.accountId,other.runId,"https://example.org/foreign","KEEP_FOREIGN");
 const reports=await Promise.all([parent.runId,child.runId,grandchild.runId,unrelated.runId].map(id=>derived(owner.accountId,id,id===unrelated.runId?"KEEP_REPORT":canary)));
 await pool.query("UPDATE runs SET counterevidence_required_revision=brief_revision WHERE id=$1",[child.runId]);
 const removed=await deleteSourceForAccount(pool,owner.accountId,target.sourceId);
 expect(new Set(removed.invalidatedRunIds)).toEqual(new Set([parent.runId,child.runId,grandchild.runId]));
 expect(await getPassageForAccount(pool,target.passageId,owner.accountId)).toBeNull();
 expect((await getPassageForAccount(pool,kept.passageId,owner.accountId)).exact_text).toBe("KEEP_RAW_SAME_RUN");
 expect((await getPassageForAccount(pool,independent.passageId,owner.accountId)).exact_text).toBe("KEEP_INDEPENDENT");
 expect((await getPassageForAccount(pool,foreignSource.passageId,foreign.accountId)).exact_text).toBe("KEEP_FOREIGN");
 expect((await pool.query("SELECT 1 FROM extraction_receipts WHERE source_version_id=$1",[target.versionId])).rowCount).toBe(0);
 expect((await pool.query("SELECT 1 FROM evidence_artifacts WHERE account_id=$1 AND digest=$2",[owner.accountId,target.document.digest])).rowCount).toBe(0);
 for(const id of removed.invalidatedRunIds){
  expect((await getRun(pool,id))).toMatchObject({lifecycle:"terminal",terminal_outcome:"cancelled"});
  expect((await pool.query("SELECT 1 FROM model_operation_results WHERE run_id=$1",[id])).rowCount).toBe(0);
  expect((await pool.query("SELECT 1 FROM run_evidence_membership WHERE run_id=$1",[id])).rowCount).toBe(0);
 }
 for(const id of reports.slice(0,3)){const report=(await pool.query("SELECT * FROM reports WHERE id=$1",[id])).rows[0];expect(report.redacted_at).not.toBeNull();expect(JSON.stringify(report)).not.toContain(canary);expect(await exportReportForAccount(pool,id,owner.accountId)).toBeNull();}
 expect(JSON.stringify((await pool.query("SELECT * FROM reports WHERE id=$1",[reports[3]])).rows)).toContain("KEEP_REPORT");
 expect((await pool.query("SELECT counterevidence_required_revision FROM runs WHERE id=$1",[child.runId])).rows[0].counterevidence_required_revision).toBe(child.briefRevision);
 await expect(admitResearchCorrection(pool,owner.accountId,parent.runId,correction(1))).rejects.toThrow("correction_parent_unavailable");
 await expect(admitRun(pool,owner.accountId,crypto.randomUUID(),CreateRunRequestSchema.parse({question,routeMode:"controlled-research",parentRunId:child.runId}))).rejects.toThrow("permission_denied");
});

it("W03 DELETE source is authenticated, owner-bound and idempotent; source reader returns its deletion handle",async()=>{
 const owner=await account(),foreign=await account(),created=await run(owner.accountId),target=await source(owner.accountId,created.runId);
 const path=`/v1/sources/${target.sourceId}`,headers={authorization:`Bearer ${owner.token}`};
 expect((await app.inject({method:"GET",url:`/v1/sources/${target.passageId}`,headers})).json().sourceId).toBe(target.sourceId);
 expect((await app.inject({method:"DELETE",url:path})).statusCode).toBe(401);
 expect((await app.inject({method:"DELETE",url:path,headers:{authorization:`Bearer ${foreign.token}`}})).statusCode).toBe(404);
 expect((await app.inject({method:"DELETE",url:"/v1/sources/not-a-uuid",headers})).statusCode).toBe(400);
 expect((await getPassageForAccount(pool,target.passageId,owner.accountId)).exact_text).toBe(canary);
 await revokeConsent(pool,owner.accountId); // Privacy removal must remain available without processing consent.
 const first=await app.inject({method:"DELETE",url:path,headers});expect(first.statusCode).toBe(200);expect(first.json()).toMatchObject({deleted:true,alreadyDeleted:false,fileCleanupPending:false});
 const epoch=(await getRun(pool,created.runId))!.cancellation_epoch;
 expect((await app.inject({method:"DELETE",url:path,headers})).json()).toMatchObject({deleted:true,alreadyDeleted:true});
 expect((await getRun(pool,created.runId))!.cancellation_epoch).toBe(epoch);
 expect((await app.inject({method:"GET",url:`/v1/sources/${target.passageId}`,headers})).statusCode).toBe(404);
 expect((await pool.query("SELECT count(*)::int n FROM tombstones WHERE account_id=$1 AND object_kind='source'",[owner.accountId])).rows[0].n).toBe(1);
});

it("W03 deletes all extraction copies of one attachment and rejects a late parser result",async()=>{
 const owner=await account(),bytes=Buffer.from(canary);
 const attachmentId=(await storeAttachment(pool,{accountId:owner.accountId,filename:"synthetic.txt",mime:"text/plain",bytes}))!;
 const parent=await run(owner.accountId,[attachmentId]),copy=await run(owner.accountId,[attachmentId]),pending=await run(owner.accountId,[attachmentId]);
 const target=await source(owner.accountId,parent.runId,`attachment://${attachmentId}`),second=await source(owner.accountId,copy.runId,`attachment://${attachmentId}`);
 const {session}=await lease(owner.accountId,pending.runId);
 let started!:()=>void,release!:()=>void;const entered=new Promise<void>(r=>started=r),wait=new Promise<void>(r=>release=r);
 vi.spyOn(extraction,"extractOffline").mockImplementation(async()=>{started();await wait;return target.document;});
 const reading=ingestAttachments(pool,{id:pending.runId,account_id:owner.accountId},{attachmentIds:[attachmentId]},session);
 const outcome=reading.then(()=>null,error=>error);await entered;
 const removed=await deleteSourceForAccount(pool,owner.accountId,target.sourceId);release();
 expect(await outcome).toBeInstanceOf(LostWorkerLease);
 expect(new Set(removed.invalidatedRunIds)).toEqual(new Set([parent.runId,copy.runId,pending.runId]));
 expect(await getPassageForAccount(pool,second.passageId,owner.accountId)).toBeNull();
 const att=(await pool.query("SELECT * FROM attachments WHERE id=$1",[attachmentId])).rows[0];
 expect(att).toMatchObject({filename:"[deleted]",size_bytes:0,raw_bytes:null,extraction:null,extracted_text:null,sha256:null,storage_ptr:"",processing_state:"deleted"});
 expect(att.deleted_at).not.toBeNull();
 expect((await pool.query("SELECT 1 FROM sources WHERE run_id=$1",[pending.runId])).rowCount).toBe(0);
 expect((await pool.query("SELECT 1 FROM evidence_artifacts WHERE account_id=$1",[owner.accountId])).rowCount).toBe(0);
 await expect(run(owner.accountId,[attachmentId])).rejects.toThrow("permission_denied");
});

it("W03 source deletion prevents late model output but preserves actual financial receipts",async()=>{
 const owner=await account(),created=await run(owner.accountId),target=await source(owner.accountId,created.runId),{session,fence}=await lease(owner.accountId,created.runId);
 let started!:()=>void,release!:()=>void;const entered=new Promise<void>(r=>started=r),wait=new Promise<void>(r=>release=r);
 globalThis.fetch=vi.fn(async()=>{started();await wait;return new Response(JSON.stringify({id:"source-deletion-model-control",model:"openai/gpt-4o-mini",provider:"OpenAI",usage:{cost:"0.000003"},choices:[{finish_reason:"stop",message:{content:JSON.stringify({privateText:canary})}}]}),{status:200});}) as typeof fetch;
 const request=performModelOperation(pool,config,session,{accountId:owner.accountId,runId:created.runId,fence,briefRevision:1,evidenceRevision:0,operation:"brief",
  context:{question,task:null,passages:[],sources:[],assertions:[],approvedClaimKeys:[],draft:null}});
 const outcome=request.then(()=>null,error=>error);await entered;
 await deleteSourceForAccount(pool,owner.accountId,target.sourceId);
 expect((await pool.query("SELECT state FROM reservations WHERE run_id=$1",[created.runId])).rows[0].state).toBe("reserved");
 release();expect(await outcome).toBeInstanceOf(LostWorkerLease);
 expect((await pool.query("SELECT 1 FROM model_operation_results WHERE run_id=$1",[created.runId])).rowCount).toBe(0);
 expect((await pool.query("SELECT state,confirmed_micro FROM provider_intents WHERE run_id=$1",[created.runId])).rows).toEqual([{state:"confirmed",confirmed_micro:"3"}]);
 expect((await pool.query("SELECT state,settled_micro FROM reservations WHERE run_id=$1",[created.runId])).rows).toEqual([{state:"settled",settled_micro:"3"}]);
 expect(fetch).toHaveBeenCalledTimes(1);
});

it("W03 source deletion drains only the selected legacy attachment file",async()=>{
 const owner=await account();
 const selected=(await storeAttachment(pool,{accountId:owner.accountId,filename:"selected.txt",mime:"text/plain",bytes:Buffer.from(canary)}))!;
 const kept=(await storeAttachment(pool,{accountId:owner.accountId,filename:"kept.txt",mime:"text/plain",bytes:Buffer.from("KEEP_FILE")}))!;
 const paths=[join(storageDir,`${owner.accountId}-${selected}`),join(storageDir,`${owner.accountId}-${kept}`)];
 await writeFile(paths[0]!,canary);await writeFile(paths[1]!,"KEEP_FILE");
 await pool.query("UPDATE attachments SET raw_bytes=NULL,storage_ptr=CASE WHEN id=$1 THEN $3 ELSE $4 END WHERE id=ANY($2::uuid[])",[selected,[selected,kept],...paths]);
 const created=await run(owner.accountId,[selected]),target=await source(owner.accountId,created.runId,`attachment://${selected}`);
 const response=await app.inject({method:"DELETE",url:`/v1/sources/${target.sourceId}`,headers:{authorization:`Bearer ${owner.token}`}});
 expect(response.statusCode).toBe(200);expect(response.json().fileCleanupPending).toBe(false);
 await expect(readFile(paths[0]!)).rejects.toMatchObject({code:"ENOENT"});
 expect(await readFile(paths[1]!,"utf8")).toBe("KEEP_FILE");
 expect((await pool.query("SELECT state,storage_ptr FROM file_deletion_outbox WHERE attachment_id=$1",[selected])).rows).toEqual([{state:"deleted",storage_ptr:""}]);
 expect((await pool.query("SELECT filename,deleted_at FROM attachments WHERE id=$1",[kept])).rows).toEqual([{filename:"kept.txt",deleted_at:null}]);
});

it("W02/W03 source deletion keeps unknown provider and account holds until actual reconciliation",async()=>{
 const owner=await account(),created=await run(owner.accountId),target=await source(owner.accountId,created.runId),{fence}=await lease(owner.accountId,created.runId);
 const scope=crypto.randomUUID(),scoped={...config,liveBudgetScope:scope};
 const attempted=await reserveLiveAttempt(pool,scoped,{runId:created.runId,fence,briefRevision:1,kind:"search",route:"openrouter:test",requestDigest:"a".repeat(64),reserveMicro:40000,logicalKey:"source-deletion-unknown-control"});
 await updateIntentState(pool,attempted.intentId,"outcome-unknown");
 const before=(await pool.query("SELECT reserved_micro FROM allowance_accounts WHERE account_id=$1",[owner.accountId])).rows[0].reserved_micro;
 await deleteSourceForAccount(pool,owner.accountId,target.sourceId);
 expect((await pool.query("SELECT state,confirmed_micro,reserved_max_micro FROM provider_intents WHERE id=$1",[attempted.intentId])).rows).toEqual([{state:"outcome-unknown",confirmed_micro:null,reserved_max_micro:"40000"}]);
 expect((await pool.query("SELECT reserved_micro FROM allowance_accounts WHERE account_id=$1",[owner.accountId])).rows[0].reserved_micro).toBe(before);
 expect(await liveSpendUsedMicro(pool,scope)).toBe(40000);
 await updateIntentState(pool,attempted.intentId,"confirmed",12000);
 expect((await pool.query("SELECT state,settled_micro FROM reservations WHERE run_id=$1",[created.runId])).rows).toEqual([{state:"settled",settled_micro:"12000"}]);
 expect(await liveSpendUsedMicro(pool,scope)).toBe(12000);
});

it("withdraws the exact admission key before source invalidation removes its run identity",async()=>{
 const owner=await account(),key=crypto.randomUUID().toUpperCase();
 const body=CreateRunRequestSchema.parse({question,routeMode:"controlled-research",attachmentIds:[]});
 const created=await admitRun(pool,owner.accountId,key,body);
 const target=await source(owner.accountId,created.runId);
 await deleteSourceForAccount(pool,owner.accountId,target.sourceId);
 await expect(admitRun(pool,owner.accountId,key,body)).rejects.toThrow("idempotency_withdrawn");
 expect((await pool.query("SELECT count(*)::int AS n FROM runs WHERE account_id=$1",[owner.accountId])).rows[0].n).toBe(1);
 expect((await pool.query("SELECT key_hash FROM admission_withdrawals WHERE account_id=$1",[owner.accountId])).rows)
  .toEqual([{key_hash:createHash("sha256").update(key).digest("hex")}]);
 expect((await pool.query("SELECT original_question FROM research_briefs WHERE account_id=$1",[owner.accountId])).rows[0].original_question).toBe("[source deleted]");
 const other=await account();
 expect((await admitRun(pool,other.accountId,key,body)).reused).toBe(false);
 expect((await admitRun(pool,owner.accountId,crypto.randomUUID(),body)).reused).toBe(false);
});
