"""Record completed checks without manufacturing outcomes; invoke after the serial suite ends."""
import pathlib,json,hashlib,subprocess,sys,datetime
root=pathlib.Path(__file__).resolve().parents[3];out=pathlib.Path(__file__).resolve().parent
serial_exit=int(sys.argv[1]);log=(out/'integration-serial.txt').read_text()
if 'Test Files' not in log:raise SystemExit('Serial suite has not finished')
commands=[
 {'command':'pnpm verify','exitCode':0,'counts':{'core':173,'backend':170,'mobile':206,'governance':6},'artifact':'verify-span.txt','scope':'Configured types, deterministic controls and boundaries; no provider execution'},
 {'command':'pnpm --filter @deep/research-core exec vitest run --config vitest.config.ts test/model-span-resolution.test.ts','exitCode':0,'tests':7,'artifact':'span-unit.txt'},
 {'command':'TEST_DATABASE_URL=postgres://deep:deep_local_dev_only@127.0.0.1:55432/deep_zdr_span_20260918 pnpm --filter @deep/backend exec vitest run --config vitest.integration.config.ts test/model-policy.integration.test.ts test/provider-reconciliation.integration.test.ts','exitCode':0,'tests':20,'artifact':'span-integration.txt','scope':'Real PostgreSQL, fabricated transports'},
 {'command':"TEST_DATABASE_URL=postgres://deep:deep_local_dev_only@127.0.0.1:55432/deep_zdr_span_20260918 EXTRACTION_RUNTIME=/tmp/deep-v6-extraction-runtime EVAL_RUNNER_ARTIFACT_DIR=/tmp/deep-zdr-span-extraction pnpm --filter @deep/backend exec vitest run --config vitest.extraction.config.ts test/eval-live.extraction.test.ts -t 'frozen .* pairs'",'exitCode':0,'selectedPassed':6,'notSelected':11,'artifact':'span-extraction.txt','scope':'Actual isolated HTML/PDF, production API/worker; fabricated model outputs and prices'},
 {'command':"TEST_DATABASE_URL=postgres://deep:deep_local_dev_only@127.0.0.1:55432/deep_zdr_span_20260918 NODE_OPTIONS='--require=/home/oranolio/Desktop/Deep/verification/v6/zdr-route/query-profile.cjs' pnpm test:integration",'exitCode':serial_exit,'artifact':'integration-serial.txt','scope':'Frozen runtime, real PostgreSQL, no concurrent test suites, query counts only; no live providers'},
 {'command':'python3 verification/v6/zdr-route/run-paid.py','exitCode':2,'artifact':'EXECUTION.json','scope':'Actual Azure model,2of4plannedsteps; no successful report'},
 {'command':'pnpm --filter @deep/backend exec tsx /home/oranolio/Desktop/Deep/verification/v6/zdr-route/check-cost.mts','exitCode':0,'artifact':'COST_CHECK.json','scope':'Actual read-only generation receipt and quota; no timeout settlement'},
 {'command':'python3 scripts/validate_review.py','exitCode':0,'artifact':'final-review.txt','scope':'Metadata only'},
 {'command':'python3 scripts/validate_builder_handoff.py','exitCode':0,'artifact':'final-handoff.txt','scope':'Metadata only'}]
paths=subprocess.check_output(['git','ls-files','apps/backend/src','apps/backend/migrations','packages/contracts/src','packages/research-core/src','apps/backend/test','packages/research-core/test'],cwd=root,text=True).splitlines()
source=[{'path':p,'sha256':hashlib.sha256((root/p).read_bytes()).hexdigest()} for p in paths if (root/p).is_file()]
result={'requirements':['W01','W02','W05','W06','W08','W09'],'runtimeCommit':'f12c2fc70c57f9413a4d017a8806724c4f6820a0','liveRuntimeCommit':json.loads((out/'EXECUTION.json').read_text())['commit'],'recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'environment':{'node':subprocess.check_output(['node','--version'],text=True).strip(),'pnpm':subprocess.check_output(['pnpm','--version'],text=True).strip(),'platform':'Linux, real local PostgreSQL, isolated parser runtime /tmp/deep-v6-extraction-runtime'},'commands':commands,'sourceFiles':source,'preservedFailures':{'integration.txt':'452pass/6fail; source edits and concurrent suites invalidate final-revision claim','timeout-recheck.txt':'2timeout failures while other suites ran','gateway-unit.txt':'Initial test response helper was not a Response; fixed without relaxing checks','types-tests.txt':'Initial test typing failures; retained','verify.txt':'Initial test cancellation arity error; retained'},'live':{'expectedSteps':4,'attempted':2,'reports':0,'correctionUnrun':True,'confirmedRawCostUsd':'0.0005388','confirmedAccountingMicro':539,'unknownHeldMicro':21658,'unknownRequestRetried':False,'semanticScores':None,'humanAdjudication':None},'rollback':'Disable new Azure/v2 admissions; retain immutable policies, consent, receipts, unknown holds, ownership/fences and publication checks','milestoneComplete':False,'releaseGates':'W10 unexecuted; no native build, hosted deployment, push or store release'}
(out/'RESULTS.json').write_text(json.dumps(result,indent=2)+'\n')
files=[{'path':str(p.relative_to(out)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(out.rglob('*')) if p.is_file() and p.name!='FILES.json']
(out/'FILES.json').write_text(json.dumps(files,indent=2)+'\n')
print(json.dumps({'files':len(files),'serialExitCode':serial_exit,'runtime':result['runtimeCommit']}))
