import { createHash } from "node:crypto";
import { afterEach,expect,it,vi } from "vitest";
import { prepareAdmission,submitAdmission,type AdmissionDraft } from "../src/admission-retry";
import { api } from "../src/api";
import { createSessionStorage,memoryStore } from "../src/persist";
import { createProtectedContentStore } from "../src/protected-content";
const digest=async(bytes:Uint8Array)=>new Uint8Array(createHash("sha256").update(bytes).digest());
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const file={filename:"private.txt",mime:"text/plain",text:"Private document bytes"};
const accepted={runId:id(50),lifecycle:"queued",phase:"planning",labeledDemo:false};
async function draft(mode:"fixture"|"controlled-research"="controlled-research"){let n=0;return prepareAdmission("Research document",mode,[file],()=>id(++n),digest);}
function io(value:unknown){return{digest,preflight:vi.fn(async()=>value),current:()=>true,progress:vi.fn(),save:vi.fn(async(_d:AdmissionDraft)=>{}),upload:vi.fn(async()=>({attachmentId:id(40)})),admit:vi.fn(async()=>accepted)};}
afterEach(()=>{api.activateSession(null);vi.unstubAllGlobals();});
for(const [mode,value] of [["controlled-research",{liveRouteEnabled:false,fixtureRouteAllowed:true}],["fixture",{liveRouteEnabled:true,fixtureRouteAllowed:false}],["controlled-research",{}],["fixture",{fixtureRouteAllowed:"true"}],["controlled-research",{liveRouteEnabled:1}],["controlled-research",null]] as const){
 it(`W03 blocks upload/admission for unavailable or unconfirmed ${mode} flag ${JSON.stringify(value)}`,async()=>{const ports=io(value);await expect(submitAdmission(await draft(mode),[file],ports)).rejects.toThrow(/mode|availability/i);expect(ports.preflight).toHaveBeenCalledTimes(1);expect(ports.save).not.toHaveBeenCalled();expect(ports.upload).not.toHaveBeenCalled();expect(ports.admit).not.toHaveBeenCalled();});
}
it.each(["fixture","controlled-research"] as const)("W07 fresh %s preflight precedes journal and upload without changing retry keys",async mode=>{const d=await draft(mode),ports=io({liveRouteEnabled:true,fixtureRouteAllowed:true});expect(await submitAdmission(d,[file],ports)).toEqual(accepted);expect(ports.preflight.mock.invocationCallOrder[0]).toBeLessThan(ports.save.mock.invocationCallOrder[0]!);expect(ports.save.mock.invocationCallOrder[0]).toBeLessThan(ports.upload.mock.invocationCallOrder[0]!);expect(ports.upload).toHaveBeenCalledWith(expect.objectContaining({text:file.text}),d.uploads[0]!.key);expect(ports.admit).toHaveBeenCalledWith(expect.objectContaining({key:d.key}),[id(40)]);});
it("W02 preflight network failure preserves cold-recoverable pending identity and confirmed uploads",async()=>{const store=createSessionStorage(createProtectedContentStore(memoryStore(),memoryStore()),memoryStore());await store.activate({accountId:"owner",token:"token"});const d=await draft();d.uploads[0]!.attachmentId=id(40);await store.saveAdmission("token",d);const ports=io({});ports.preflight.mockRejectedValue(new Error("preflight offline"));await expect(submitAdmission(d,[],ports)).rejects.toThrow("preflight offline");expect((await store.hydrate()).state.pendingAdmission).toEqual(d);expect(ports.save).not.toHaveBeenCalled();expect(ports.admit).not.toHaveBeenCalled();});
it.each(["account","view"])("W03 ignores late preflight after %s generation changes",async kind=>{const d=await draft();api.activateSession("owner");api.selectRun("old");const guard=api.captureView();let resolve!:(value:Response)=>void;const response=new Promise<Response>(r=>{resolve=r;});vi.stubGlobal("fetch",vi.fn(()=>response));const ports={...io({}),current:guard.current,preflight:()=>api.settings("owner")};const pending=submitAdmission(d,[file],ports);const rejected=expect(pending).rejects.toThrow("superseded");if(kind==="account")api.activateSession("other");else api.selectRun("other");resolve(Response.json({accountId:"owner",authMode:"development",liveRouteEnabled:true,fixtureRouteAllowed:true}));await rejected;expect(ports.save).not.toHaveBeenCalled();expect(ports.upload).not.toHaveBeenCalled();expect(ports.admit).not.toHaveBeenCalled();guard.release();});
it("W02 Check/Withdraw still resolves an accepted unknown request while scheduling is disabled",async()=>{api.activateSession("owner");const calls:string[]=[];vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);calls.push(url);if(url.endsWith("/v1/settings"))return Response.json({accountId:"owner",authMode:"development",liveRouteEnabled:false,fixtureRouteAllowed:false});if(url.endsWith("/v1/run-requests/resolve"))return Response.json({status:"accepted",run:accepted});throw Error("unexpected route");}));const ports={...io({}),preflight:()=>api.settings("owner")};const d=await draft();d.uploads[0]!.attachmentId=id(40);await expect(submitAdmission(d,[],ports)).rejects.toThrow(/mode/i);expect(await api.resolveRunRequest("owner",d.key)).toEqual({status:"accepted",run:accepted});expect(calls.map(c=>new URL(c).pathname)).toEqual(["/v1/settings","/v1/run-requests/resolve"]);expect(ports.admit).not.toHaveBeenCalled();});
